before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
#    - windows
  goarch:
    - amd64
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
archives:
- format_overrides:
    - goos: windows
      format: zip
release:
  github:
  prerelease: auto
dockers:
  -
    image_templates:
    - "ghcr.io/fox-one/seed/{{ .ProjectName }}:latest"
    - "ghcr.io/fox-one/seed/{{ .ProjectName }}:{{ .Major }}"
    - "ghcr.io/fox-one/seed/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/fox-one/seed/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
